apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
    tier: frontend
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress-container
        env:
        - name: WORDPRESS_DB_HOST
          value: mysqlserver-for-wordpress.mysql.database.azure.com
        - name: WORDPRESS_DB_PASSWORD
          value: ShiVVaMm-#-@@@@2102
        - name: WORDPRESS_DB_USER
          value: shivam@mysqlserver-for-wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress-db
        ports:
        - containerPort: 80
          name: wordpress